import { Achievement, AvatarOption, MapNode, PlayerProfile, Quest, RandomEvent, ShopItem } from '../types/quest';

export const AVATAR_OPTIONS: AvatarOption[] = [
  {
    id: 'cyber_mage',
    name: 'Cyber Mage',
    title: 'Arcane Data Weaver',
    emoji: '🧙‍♂️',
    description: 'Masters the digital realm through calculated study & caffeinated spells.',
    color: 'from-purple-500 to-indigo-600',
    bgGradient: 'bg-gradient-to-br from-purple-950/80 via-purple-900/40 to-black',
  },
  {
    id: 'solar_paladin',
    name: 'Solar Paladin',
    title: 'Champion of High Energy',
    emoji: '⚔️',
    description: 'Crushes morning lethargy with sheer discipline and righteous momentum.',
    color: 'from-amber-400 to-yellow-600',
    bgGradient: 'bg-gradient-to-br from-amber-950/80 via-yellow-900/40 to-black',
  },
  {
    id: 'coffee_alchemist',
    name: 'Coffee Alchemist',
    title: 'Brewmaster of Focus',
    emoji: '☕',
    description: 'Transmutes roasted beans into bursts of pure hyper-productivity.',
    color: 'from-emerald-500 to-teal-700',
    bgGradient: 'bg-gradient-to-br from-emerald-950/80 via-teal-900/40 to-black',
  },
  {
    id: 'pixel_bard',
    name: 'Pixel Bard',
    title: 'Lord of Vibes & Banter',
    emoji: '🎸',
    description: 'Turns boring group study sessions into legendary party adventures.',
    color: 'from-pink-500 to-rose-600',
    bgGradient: 'bg-gradient-to-br from-pink-950/80 via-rose-900/40 to-black',
  },
  {
    id: 'neon_ninja',
    name: 'Neon Ninja',
    title: 'Stealth Executioner',
    emoji: '🥷',
    description: 'Silently executes tasks before the Procrastination Monster even notices.',
    color: 'from-cyan-400 to-blue-600',
    bgGradient: 'bg-gradient-to-br from-cyan-950/80 via-blue-900/40 to-black',
  },
  {
    id: 'chaos_goblin',
    name: 'Chaos Goblin',
    title: 'Gremlin of Spontaneity',
    emoji: '😈',
    description: 'Thrives in unpredictable situations and turns mundane days into folklore.',
    color: 'from-red-500 to-orange-600',
    bgGradient: 'bg-gradient-to-br from-red-950/80 via-orange-900/40 to-black',
  },
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_quest',
    title: 'FIRST QUEST',
    description: 'Complete your first quest and take your first step as a real-life hero.',
    icon: '🏆',
    category: 'beginner',
    unlocked: true,
    unlockedAt: 'Today',
    xpReward: 50,
    coinReward: 20,
    progress: 100,
    requirementText: '1/1 Quest Completed',
  },
  {
    id: 'quest_hunter',
    title: 'QUEST HUNTER',
    description: 'Complete 5 quests in a single day.',
    icon: '⚔️',
    category: 'mastery',
    unlocked: false,
    xpReward: 150,
    coinReward: 60,
    progress: 60,
    requirementText: '3/5 Quests Completed',
  },
  {
    id: 'unstoppable_streak',
    title: 'UNSTOPPABLE STREAK',
    description: 'Maintain an active adventure streak for 4 or more days.',
    icon: '🔥',
    category: 'mastery',
    unlocked: true,
    unlockedAt: 'Yesterday',
    xpReward: 200,
    coinReward: 80,
    progress: 100,
    requirementText: '4/4 Day Streak',
  },
  {
    id: 'procrastination_slayer',
    title: 'PROCRASTINATION SLAYER',
    description: 'Conquer a hard or epic main quest before 5:00 PM.',
    icon: '💀',
    category: 'mastery',
    unlocked: false,
    xpReward: 250,
    coinReward: 100,
    progress: 0,
    requirementText: 'Defeat 1 Main Boss Quest',
  },
  {
    id: 'touch_grass',
    title: 'TOUCH GRASS',
    description: 'Complete 3 outdoor or exploration quests.',
    icon: '🌱',
    category: 'exploration',
    unlocked: true,
    unlockedAt: '2 days ago',
    xpReward: 120,
    coinReward: 50,
    progress: 100,
    requirementText: '3/3 Exploration Quests',
  },
  {
    id: 'social_butterfly',
    title: 'SOCIAL BUTTERFLY',
    description: 'Engage with friends or random NPCs across 5 social encounters.',
    icon: '❤️',
    category: 'social',
    unlocked: false,
    xpReward: 160,
    coinReward: 70,
    progress: 80,
    requirementText: '4/5 Social Quests',
  },
  {
    id: 'chaos_enjoyer',
    title: 'CHAOS ENJOYER',
    description: 'Activate Chaos Mode and survive 2 surprise chaos events.',
    icon: '😈',
    category: 'chaos',
    unlocked: false,
    xpReward: 180,
    coinReward: 75,
    progress: 50,
    requirementText: '1/2 Chaos Events',
  },
  {
    id: 'perfect_day_legend',
    title: 'PERFECT DAY',
    description: 'Clear the Main Quest + 3 Side Quests + 1 Secret Quest in a single day.',
    icon: '👑',
    category: 'legendary',
    unlocked: false,
    xpReward: 500,
    coinReward: 250,
    progress: 60,
    requirementText: 'Complete full adventure deck',
  },
];

export const INITIAL_SHOP_ITEMS: ShopItem[] = [
  {
    id: 'wizard_hat',
    name: 'Archmage Wizard Hat',
    type: 'head',
    icon: '🎩',
    price: 150,
    description: 'Grants +10% perceived intelligence while reading dense textbooks.',
    rarity: 'rare',
    perkText: '+5% XP on study quests',
  },
  {
    id: 'cool_shades',
    name: 'Cyberpunk Neon Shades',
    type: 'head',
    icon: '🕶️',
    price: 100,
    description: 'Guaranteed to make walking across campus look like a cinematic trailer.',
    rarity: 'common',
    perkText: '+10 Aura in social quests',
  },
  {
    id: 'flame_crown',
    name: 'Crown of Daily Momentum',
    type: 'head',
    icon: '👑',
    price: 500,
    description: 'Forged in the fires of completed deadlines. Pure royalty.',
    rarity: 'legendary',
    perkText: '+20% Streak multiplier',
  },
  {
    id: 'fire_aura',
    name: 'Super Saiyan Fire Aura',
    type: 'aura',
    icon: '🔥',
    price: 300,
    description: 'A crackling flame aura that terrifies procrastinators in a 10m radius.',
    rarity: 'epic',
    perkText: 'Glows on your avatar card',
  },
  {
    id: 'cyber_cat',
    name: 'Pixel Cyber Cat',
    type: 'companion',
    icon: '🐱',
    price: 250,
    description: 'A loyal digital familiar that judges you gently when you open TikTok.',
    rarity: 'rare',
    perkText: 'Meows when you finish a quest',
  },
  {
    id: 'dragon_hatchling',
    name: 'Pocket Flame Dragon',
    type: 'companion',
    icon: '🐲',
    price: 600,
    description: 'Roasts your excuses into fine dust. Loves shiny Quest Coins.',
    rarity: 'legendary',
    perkText: '+15 Bonus coins per quest',
  },
  {
    id: 'golden_sword',
    name: 'Excalibur of Productivity',
    type: 'weapon',
    icon: '⚔️',
    price: 400,
    description: 'One slice splits any overwhelming 10-page essay into bite-sized tasks.',
    rarity: 'epic',
    perkText: '+10% Focus power',
  },
  {
    id: 'title_chaos_tamer',
    name: 'Title: The Chaos Tamer',
    type: 'title',
    icon: '🏷️',
    price: 120,
    description: 'Equip this title to show everyone you survived college group projects.',
    rarity: 'rare',
    perkText: 'Equippable player title',
  },
  {
    id: 'title_main_char',
    name: 'Title: Main Character',
    type: 'title',
    icon: '✨',
    price: 350,
    description: 'You are no longer an NPC. The universe revolves around your quest line.',
    rarity: 'legendary',
    perkText: 'Shimmering golden title',
  },
];

export const DEMO_QUESTS: Quest[] = [
  {
    id: 'quest-boss-1',
    title: 'DEFEAT THE FINAL BOSS',
    subtitle: 'Main Objective: Project Presentation',
    description: 'Polish and finalize the hackathon demo slides and test every single user flow.',
    flavorText: 'The Final Boss stands between you and glory. Do not flinch, hero.',
    category: 'main',
    difficulty: 'epic',
    xpReward: 350,
    coinReward: 90,
    status: 'in_progress',
    isMainQuest: true,
    timeEstimateMinutes: 45,
    location: 'Battle Station',
    icon: '🐉',
    comboType: 'productivity',
    steps: [
      'Draft key demo slides',
      'Rehearse the 3-minute pitch',
      'Test live edge-cases with audio'
    ],
    currentStepIndex: 1,
  },
  {
    id: 'quest-side-1',
    title: 'KNOWLEDGE DUNGEON',
    subtitle: 'Deep Focus Sprint',
    description: 'Survive 45 minutes of hyper-focused study/coding without opening social media.',
    flavorText: 'Instagram siren calls echo through the stone halls. Resist them!',
    category: 'side',
    difficulty: 'medium',
    xpReward: 120,
    coinReward: 35,
    status: 'completed',
    completedAt: '10:15 AM',
    timeEstimateMinutes: 45,
    location: 'Study Chamber',
    icon: '📚',
    comboType: 'productivity',
  },
  {
    id: 'quest-side-2',
    title: 'RECHARGE HP AT OASIS',
    subtitle: 'Hydration & Mindful Break',
    description: 'Drink 500ml of fresh water, step away from all screens, and do 5 deep breaths.',
    flavorText: 'Your stamina meter was blinking red. Drink the magical elixir.',
    category: 'recovery',
    difficulty: 'easy',
    xpReward: 60,
    coinReward: 15,
    status: 'completed',
    completedAt: '11:30 AM',
    timeEstimateMinutes: 10,
    location: 'Water Fountain Oasis',
    icon: '💧',
    comboType: 'wellness',
  },
  {
    id: 'quest-side-3',
    title: 'NPC ENCOUNTER',
    subtitle: 'Social Quest',
    description: 'Reach out to a classmate or friend you haven’t texted all week and send a funny meme or quick check-in.',
    flavorText: 'Villagers possess valuable side quests and high-tier morale buffs.',
    category: 'social',
    difficulty: 'easy',
    xpReward: 80,
    coinReward: 25,
    status: 'completed',
    completedAt: '1:00 PM',
    timeEstimateMinutes: 5,
    location: 'Campus Courtyard',
    icon: '💬',
    comboType: 'social',
  },
  {
    id: 'quest-exp-1',
    title: 'UNCHARTED TERRITORY',
    subtitle: 'Campus Discovery',
    description: 'Walk down a hallway or visit a campus corner you have NEVER entered before and inspect what is there.',
    flavorText: 'Fog of war covers 80% of your campus map. Uncover the secrets.',
    category: 'exploration',
    difficulty: 'medium',
    xpReward: 140,
    coinReward: 40,
    status: 'available',
    timeEstimateMinutes: 20,
    location: 'East Wing Basement',
    icon: '🧭',
    comboType: 'exploration',
  },
  {
    id: 'quest-chaos-1',
    title: 'CHAOS CARD: WEIRD SNACK TASTING',
    subtitle: 'Spontaneous Gastronomy',
    description: 'Purchase a beverage or snack flavor you would normally NEVER buy and review it like a Michelin inspector.',
    flavorText: 'The Chaos Gods demand culinary bravery.',
    category: 'random',
    difficulty: 'medium',
    xpReward: 110,
    coinReward: 30,
    status: 'available',
    isChaos: true,
    timeEstimateMinutes: 15,
    location: 'Vending Dungeon',
    icon: '🎲',
    comboType: 'creative',
  },
  {
    id: 'quest-secret-1',
    title: 'THE GOLDEN MOMENT',
    subtitle: 'Locked Mystery Quest',
    description: 'Do one spontaneous generous act or creative snapshot today that you will vividly remember 1 year from now.',
    flavorText: 'A golden glow emanates from this sealed scroll...',
    category: 'secret',
    difficulty: 'hard',
    xpReward: 220,
    coinReward: 75,
    status: 'locked',
    isSecret: true,
    secretUnlockRequirement: 'Complete 3 Quests to unlock (3/3 Complete! Ready to unlock ✨)',
    icon: '🔒',
    comboType: 'wellness',
  },
];

export const DEMO_PLAYER_PROFILE: PlayerProfile = {
  name: 'Alex Vance',
  avatar: 'cyber_mage',
  title: 'The Chaos Tamer',
  level: 6,
  currentXp: 840,
  xpToNextLevel: 1000,
  coins: 320,
  streak: 4,
  totalQuestsCompleted: 47,
  chaosMode: true,
  soundEnabled: true,
  stats: {
    productivity: 85,
    social: 60,
    exploration: 75,
    creativity: 70,
    wellness: 80,
  },
  inventory: ['cool_shades', 'wizard_hat', 'title_chaos_tamer'],
  equippedCosmetics: {
    head: 'cool_shades',
    title: 'The Chaos Tamer',
    companion: 'cyber_cat',
    aura: 'fire_aura',
  },
};

export const DEMO_MAP_NODES: MapNode[] = [
  {
    id: 'node-1',
    name: 'MORNING GATE',
    subtitle: 'Sunrise Awakening',
    icon: '🌅',
    type: 'gate',
    status: 'completed',
    xpReward: 50,
    lore: 'You crossed the threshold of bed sheets and stepped into the sunlight.',
  },
  {
    id: 'node-2',
    name: 'KNOWLEDGE DUNGEON',
    subtitle: 'Study Chamber of Lore',
    icon: '📚',
    type: 'dungeon',
    status: 'completed',
    connectedQuestId: 'quest-side-1',
    xpReward: 120,
    lore: 'Ancient textbooks and code repositories conquered without hesitation.',
  },
  {
    id: 'node-3',
    name: 'REST OASIS',
    subtitle: 'Potion Brewery & Chill',
    icon: '💧',
    type: 'camp',
    status: 'completed',
    connectedQuestId: 'quest-side-2',
    xpReward: 60,
    lore: 'HP restored, thirst quenched, mental clarity rebooted.',
  },
  {
    id: 'node-4',
    name: 'EXPLORER’S FOREST',
    subtitle: 'Uncharted Campus Trail',
    icon: '🌲',
    type: 'forest',
    status: 'current',
    connectedQuestId: 'quest-exp-1',
    xpReward: 140,
    lore: 'The rustling trees hold mysteries yet to be documented.',
  },
  {
    id: 'node-5',
    name: 'CHAOS RIFT',
    subtitle: 'Realm of the Unpredictable',
    icon: '🎲',
    type: 'mystery',
    status: 'locked',
    connectedQuestId: 'quest-chaos-1',
    xpReward: 110,
    lore: 'A swirling portal of strange decisions and wild encounters.',
  },
  {
    id: 'node-6',
    name: 'THE CITADEL BOSS',
    subtitle: 'Final Presentation Battle',
    icon: '🏰',
    type: 'boss',
    status: 'locked',
    connectedQuestId: 'quest-boss-1',
    xpReward: 350,
    lore: 'The ultimate climax of your day. Victory echoes throughout the kingdom.',
  },
  {
    id: 'node-7',
    name: 'NIGHT SANCTUARY',
    subtitle: 'Legendary Rest & Recap',
    icon: '🌙',
    type: 'kingdom',
    status: 'locked',
    xpReward: 100,
    lore: 'Where tired heroes count their coins and celebrate their glory.',
  },
];

export const RANDOM_SURPRISE_EVENTS: RandomEvent[] = [
  {
    id: 'event-free-time',
    title: 'TIME WARP: UNEXPECTED 25 MINUTES!',
    type: 'free_time',
    description: 'A lecture got canceled or a meeting ended early. The universe has gifted you 25 bonus minutes.',
    flavorText: 'Do not squander the chronomancer’s gift by doomscrolling.',
    icon: '⏰',
    choices: [
      {
        id: 'choice-grind',
        label: '⚡ SPEEDRUN STUDY (Focus)',
        description: 'Knock out 20 flashcards or review one chapter module.',
        icon: '🧠',
        xpBonus: 80,
        coinBonus: 25,
      },
      {
        id: 'choice-explore',
        label: '🗺️ RAPID EXPEDITION (Explore)',
        description: 'Take a brisk power-walk to that distant building.',
        icon: '🚶',
        xpBonus: 70,
        coinBonus: 20,
      },
      {
        id: 'choice-powernap',
        label: '😴 MEDITATION / CAT NAP (Restore)',
        description: 'Close your eyes for 15 minutes of pure HP restoration.',
        icon: '🧘',
        xpBonus: 60,
        coinBonus: 15,
      },
      {
        id: 'choice-chaos',
        label: '😈 CHAOS CALL (Social)',
        description: 'FaceTime a friend with an unhinged filter.',
        icon: '🎭',
        xpBonus: 90,
        coinBonus: 30,
      },
    ],
  },
  {
    id: 'event-weather-shift',
    title: 'THE SUNNY WINDOW OF DESTINY',
    type: 'weather',
    description: 'The weather outside is unexpectedly glorious. The indoor fluorescent lights are draining your spirit.',
    flavorText: 'Photosynthesis grants +50% morale to organic beings.',
    icon: '☀️',
    choices: [
      {
        id: 'choice-sun',
        label: '🌳 TAKE WORK OUTSIDE',
        description: 'Sit on the lawn or outdoor bench with your laptop/book.',
        icon: '📖',
        xpBonus: 100,
        coinBonus: 30,
      },
      {
        id: 'choice-iced-coffee',
        label: '🥤 ICED POTION RUN',
        description: 'Grab an iced beverage and enjoy a sunny stroll.',
        icon: '🧋',
        xpBonus: 75,
        coinBonus: 20,
      },
    ],
  },
  {
    id: 'event-friend-wild',
    title: 'WILD NPC APPEARED!',
    type: 'friend_alert',
    description: 'A friend just waved from across the hall and looks ready for lunch or a diversion.',
    flavorText: 'Co-op multiplayer mode is ready to activate.',
    icon: '👥',
    choices: [
      {
        id: 'choice-join-party',
        label: '🍕 JOIN ADVENTURE PARTY',
        description: 'Grab food together and share side quests.',
        icon: '🤝',
        xpBonus: 120,
        coinBonus: 40,
      },
      {
        id: 'choice-quick-emote',
        label: '👋 GREET & POWER THROUGH',
        description: 'High-five them, trade quick banter, keep your study momentum.',
        icon: '⚡',
        xpBonus: 70,
        coinBonus: 20,
      },
    ],
  },
];
